### ISSUE TITLE
[Hacktoberfest] Wire up the boilerplate with Redux

### ISSUE THREAD

**Issue by levsthings** [MisaOgura/react-express-docker-boilerplate#3]
This looks like a very neat minimalist boilerplate! 

Once boilerplates start adding route handling, things get complex and I think it's very good that it's up to the user to add those based on requirements. Having said that, I think adding `redux` and `react-redux` would be pretty good. What do you think?

**Comment by MisaOgura** [comment]
Thanks for your feedback!

And indeed, wiring it up with `redux` and `react-redux` to have a skeleton for a redux app is definitely something I plan to in the near future 👍

**Comment by sammorrow** [comment]
Hey, I tackled this for Hacktoberfest. Put up a pull request, let me know if I should change anything.
